spring:
  main:
    allow-circular-references: true
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/padel?useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    password: Rootroot
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: 'true'
        show_sql: 'false'
    hibernate:
      ddl-auto: update